anguage: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"


install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - nosetests --with-coverage

after-success:
  - coveralls